

-- ---- patients ----
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('EPR_MBH_001', 'EPILEPSIE', '2020-01-15', 1.8);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('EPR_MBH_002', 'EPILEPSIE', '2020-01-15', 1.8);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('EPR_MBH_005', 'EPILEPSIE', '2024-11-01', 8);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('EPR_AZ_004', 'EPILEPSIE', '2022-06-20', 9);

-- ---- epr_identification_clinique ----
INSERT INTO epr_identification_clinique (pseudonyme, age_debut_crises_mois, age_diagnostic_pharmacoresistance_mois) VALUES ('EPR_MBH_001', 0.1, 22);
INSERT INTO epr_identification_clinique (pseudonyme, age_debut_crises_mois, age_diagnostic_pharmacoresistance_mois) VALUES ('EPR_MBH_002', 0.1, 22);
INSERT INTO epr_identification_clinique (pseudonyme, age_debut_crises_mois, age_diagnostic_pharmacoresistance_mois) VALUES ('EPR_MBH_005', 21, 96);
INSERT INTO epr_identification_clinique (pseudonyme, age_debut_crises_mois, age_diagnostic_pharmacoresistance_mois) VALUES ('EPR_AZ_004', 72, 96);

-- ---- epr_antecedents ----
INSERT INTO epr_antecedents (pseudonyme, atcd_perinataux, atcd_perinataux_precision, consanguinite_parentale, consanguinite_degre, atcd_familiaux_epilepsie, atcd_familiaux_lien, developpement_psychomoteur_avant_crises) VALUES ('EPR_MBH_001', TRUE, 'Grossesse gemellaire spontanee, cesarienne a 35 SA pour RCF pathologique (prematurite induite), Apgar 8-9-10, poids naissance 1700g, taille 46cm, PC 33cm, retard de croissance intra-uterin disharmonieux, hospitalisation 3 jours en neonatologie', FALSE, NULL, TRUE, 'Mere : crise epileptique en fin de grossesse sous Levetiracetam, sans recidive, bilan etiologique negatif. Frere jumeau EPR_MBH_002 suivi pour la meme encephalopathie epileptique genetique (mutation KCNQ2), decede en juin 2022. Autre frere de 7 ans en bonne sante apparente.', 'Retard');
INSERT INTO epr_antecedents (pseudonyme, atcd_perinataux, atcd_perinataux_precision, consanguinite_parentale, consanguinite_degre, atcd_familiaux_epilepsie, atcd_familiaux_lien, developpement_psychomoteur_avant_crises) VALUES ('EPR_MBH_002', TRUE, 'Grossesse gemellaire spontanee, cesarienne a 35 SA pour souffrance foetale aigue (RCF pathologique), Apgar 8-9-10, poids naissance 2420g, taille 47cm, PC 33cm, detresse respiratoire neonatale transitoire (CPAP 2 jours), osteomyelite du col femoral gauche traitee par antibiotherapie 60 jours + drainage chirurgical, pneumopathie a 11 mois', FALSE, NULL, TRUE, 'Mere : crise epileptique en cours de grossesse sous Levetiracetam, sans recidive, bilan etiologique negatif. Frere jumeau EPR_MBH_001 suivi pour la meme encephalopathie epileptique genetique (mutation KCNQ2). Autre frere de 7 ans en bonne sante apparente.', 'Retard');
INSERT INTO epr_antecedents (pseudonyme, atcd_perinataux, atcd_perinataux_precision, consanguinite_parentale, consanguinite_degre, atcd_familiaux_epilepsie, atcd_familiaux_lien, developpement_psychomoteur_avant_crises) VALUES ('EPR_MBH_005', FALSE, 'Cesarienne a terme pour uterus cicatriciel, pas de souffrance perinatale, poids naissance 3900g, pas de sejour en neonatologie', TRUE, 'Consanguinite parentale lointaine (grands-parents cousins de la meme region)', TRUE, 'Epilepsie et deficience intellectuelle, handicap moteur chez un cousin paternel (en rapport avec une souffrance perinatale) ; deficience intellectuelle et handicap moteur chez un autre cousin paternel ; 2 freres en bonne sante ; pas de deces en bas age dans la famille', 'Normal');
INSERT INTO epr_antecedents (pseudonyme, atcd_perinataux, atcd_perinataux_precision, consanguinite_parentale, consanguinite_degre, atcd_familiaux_epilepsie, atcd_familiaux_lien, developpement_psychomoteur_avant_crises) VALUES ('EPR_AZ_004', FALSE, 'Cesarienne a terme pour uterus cicatriciel, pas de souffrance perinatale, anemie ferriprive traitee', FALSE, NULL, FALSE, 'Pas d''antecedents familiaux d''epilepsie ou de maladie neurologique. Mere avec paralysie faciale peripherique droite en 2018. Soeur de 7 ans en bonne sante apparente.', 'Retard');

-- ---- epr_type_crise ----
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_001', '2020-01-15', 'Generalisee', 'Toniques neonatales, revulsion oculaire, cyanose faciale', 'Apyrexie (periode neonatale)');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_001', '2020-06-01', 'Generalisee', 'Myoclonies audiogenes, spasmes en flexion, clonies palpebrales, crises hypertoniques', 'Episodes grippaux, poussees dentaires');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_002', '2020-01-15', 'Generalisee', 'Crises toniques neonatales, revulsion oculaire, cyanose faciale', 'Apyrexie (periode neonatale)');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_002', '2022-05-07', 'Focale a bilateralisation', 'Crises toniques asymetriques a predominance gauche, myoclonies audiogenes, etat de mal epileptique', 'Arret du Levetiracetam par la famille');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_005', '2020-01-01', 'Focale', 'Rupture de conscience breve avec hypotonie des 4 membres et confusion post-critique', 'Aucun identifie (apyrexie)');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_MBH_005', '2024-11-01', 'Focale avec alteration de conscience', 'Aura non exprimee, automatismes gestuels (recherche d''un lieu securise), ecartement/rapprochement des genoux, hypertonie des 4 membres, rires gelastiques, fixite du regard, crampes post-critiques (60-90 secondes)', NULL);
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_AZ_004', '2019-08-01', 'Generalisee', 'Perte de connaissance breve avec resolution du tonus, sans hypertonie ni revulsion oculaire', 'Apyrexie');
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_AZ_004', '2020-02-01', 'Generalisee', 'Crises toniques generalisees avec fixite du regard et hypertonie des 4 membres', NULL);
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_AZ_004', '2022-06-20', 'Generalisee', 'Crises atoniques et probables myoclono-atoniques (lachage d''objets)', NULL);
INSERT INTO epr_type_crise (pseudonyme, date_observation, type_crise_ilae2017, sous_type, facteurs_declenchants) VALUES ('EPR_AZ_004', '2023-07-18', 'Focale a bilateralisation possible', 'Chute de la tete, vocalisation, hoquet', 'Inobservance therapeutique (arret 2 jours)');

-- ---- epr_frequence_crises ----
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_001', '2020-01-15', NULL, NULL, 20, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_001', '2024-10-15', NULL, NULL, 0, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_002', '2020-01-15', NULL, NULL, 20, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_002', '2020-01-20', NULL, NULL, 100, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_002', '2022-05-01', NULL, NULL, 3, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_005', '2024-11-01', NULL, NULL, 1, 'crises/jour', 1.25);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_MBH_005', '2025-01-15', NULL, NULL, 0, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2021-02-01', NULL, NULL, 4, 'crises/mois', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2021-10-01', NULL, NULL, 3, 'crises/semaine', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2022-06-20', NULL, NULL, 1.5, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2023-01-18', NULL, NULL, 1, 'crises/semaine', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2023-11-15', NULL, NULL, 3.5, 'crises/mois', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2025-05-16', NULL, NULL, 3, 'crises/jour', NULL);
INSERT INTO epr_frequence_crises (pseudonyme, date_rapport, periode_debut, periode_fin, frequence_crises, unite_frequence, duree_moyenne_min) VALUES ('EPR_AZ_004', '2026-05-15', NULL, NULL, 1.5, 'crises/jour', NULL);

-- ---- epr_examen ----
INSERT INTO epr_examen (pseudonyme, date_examen, neuro_eveil_reactivite, neuro_langage, neuro_comportement, neuro_marche, neuro_station_debout, neuro_tonus, neuro_force_motrice, neuro_reflexes, neuro_mouvements_anormaux, poids_kg, taille_cm, perimetre_cranien_cm, lesions_cutanees, deformations_osseuses, dysmorphie_faciale) VALUES ('EPR_MBH_001', '2020-01-15', 'Reagit aux stimuli sonores, Glasgow 15/15', 'Retard severe du langage', 'Mauvais contact social', 'Non acquise', 'Non acquise, hypotonie axiale, tenue de tete impossible', 'Hypotonie axiale et segmentaire, exageration du ballant des membres inferieurs', NULL, 'ROT vifs diffuses aux membres inferieurs, RCP indifferent', 'Nystagmus horizontal bilateral, attitude en batracien, mauvaise poursuite oculaire', 8, 80, 46, NULL, 'Scoliose dorsolombaire, chevauchement du 2e orteil bilateral, hypertrophie gingivale', 'Presente (non detaillee)');
INSERT INTO epr_examen (pseudonyme, date_examen, neuro_eveil_reactivite, neuro_langage, neuro_comportement, neuro_marche, neuro_station_debout, neuro_tonus, neuro_force_motrice, neuro_reflexes, neuro_mouvements_anormaux, poids_kg, taille_cm, perimetre_cranien_cm, lesions_cutanees, deformations_osseuses, dysmorphie_faciale) VALUES ('EPR_MBH_002', '2020-01-15', 'Reagit aux stimuli sonores, Glasgow 15/15', 'Retard severe du langage', 'Mauvais contact social', 'Non acquise', 'Non acquise, hypotonie axiale, tenue de tete impossible', 'Hypotonie axiale et segmentaire, exageration du ballant des membres inferieurs', NULL, 'ROT vifs diffuses aux membres inferieurs, signe de Rossolimo present, RCP en flexion', 'Nystagmus horizontal, open jaw dystonia, attitude en batracien', 8, 76, 47, 'Hypertrophie gingivale, cicatrice chirurgicale hanche gauche', 'Scoliose dorsolombaire, limitation de la rotation externe de hanche gauche, chevauchement du 2e orteil bilateral', NULL);
INSERT INTO epr_examen (pseudonyme, date_examen, neuro_eveil_reactivite, neuro_langage, neuro_comportement, neuro_marche, neuro_station_debout, neuro_tonus, neuro_force_motrice, neuro_reflexes, neuro_mouvements_anormaux, poids_kg, taille_cm, perimetre_cranien_cm, lesions_cutanees, deformations_osseuses, dysmorphie_faciale) VALUES ('EPR_MBH_005', '2024-11-01', 'Correct', 'Langage enfantin limite a des phrases simples (forte presomption de deficience intellectuelle)', 'Pas de trouble du comportement objective, pas d''hyperactivite', 'Autonome et stable', 'Stable', 'Normal', 'Pas de deficit moteur', 'Presents et symetriques, pas de trouble de la coordination', 'Aucun, examen des paires craniennes normal', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO epr_examen (pseudonyme, date_examen, neuro_eveil_reactivite, neuro_langage, neuro_comportement, neuro_marche, neuro_station_debout, neuro_tonus, neuro_force_motrice, neuro_reflexes, neuro_mouvements_anormaux, poids_kg, taille_cm, perimetre_cranien_cm, lesions_cutanees, deformations_osseuses, dysmorphie_faciale) VALUES ('EPR_AZ_004', '2023-07-18', 'Bien oriente, conscient', NULL, 'Deficience intellectuelle, pas de trouble du comportement ni hyperactivite', 'Autonome, stable (marche sur talons, pointes de pied, en tandem)', 'Stable, pas de signe de Romberg', 'Normal', 'Pas de deficit moteur (Barre et Mingazzini negatifs)', 'ROT presents et symetriques, RCP en flexion, pas de signe de Hoffman ni de Rossolimo', 'Aucun', 55, NULL, NULL, 'Pas de taches cafe au lait', NULL, 'Absente');

-- ---- epr_etiologie ----
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_MBH_001', 'Genetique', TRUE, NULL, 'Mutation KCNQ2 (encephalopathie epileptique et developpementale liee a KCNQ2)', NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_MBH_002', 'Genetique', TRUE, NULL, 'Mutation KCNQ2 (encephalopathie epileptique et developpementale liee a KCNQ2)', NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_MBH_005', 'Inconnue', TRUE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_MBH_005', 'Structurelle', FALSE, 'Suspicion de dysplasie corticale non confirmee ; IRM standard normale ; PET scan demande', NULL, NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_MBH_005', 'Genetique', FALSE, NULL, 'Genes candidats evoques pour dysplasie corticale : STRADA, NPRL2, NPRL3, STXBP1, SCN2A, DEPDC5 (panel PAGEM demande, non realise au moment du dossier)', NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_AZ_004', 'Inconnue', TRUE, NULL, NULL, NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_AZ_004', 'Structurelle', FALSE, 'IRM cerebrale normale (05/11/2020), cause structurelle ecartee', NULL, NULL, NULL, NULL);
INSERT INTO epr_etiologie (pseudonyme, categorie_etiologique, etiologie_principale, detail_lesion_structurelle, detail_gene_mute, detail_maladie_metabolique, detail_facteur_infectieux, detail_maladie_auto_immune) VALUES ('EPR_AZ_004', 'Genetique', FALSE, NULL, 'Genes evoques : GRIN2A (POCS) ; SCN1A, SCN1B, SCN2A, STX1B, SCN6A1, CHD2 (epilepsie myoclono-atonique) ; SLC2A1/GLUT1 ; caryotype et etude genique complementaire proposes, resultats non retrouves dans le dossier', NULL, NULL, NULL);

-- ---- epr_regression_developpementale ----
INSERT INTO epr_regression_developpementale (pseudonyme, presence_regression, date_observee) VALUES ('EPR_MBH_005', TRUE, '2020-01-01');
INSERT INTO epr_regression_developpementale (pseudonyme, presence_regression, date_observee) VALUES ('EPR_AZ_004', FALSE, NULL);

-- ---- epr_pharmacoresistance ----
INSERT INTO epr_pharmacoresistance (pseudonyme, statut_pharmacoresistance_confirme) VALUES ('EPR_MBH_001', TRUE);
INSERT INTO epr_pharmacoresistance (pseudonyme, statut_pharmacoresistance_confirme) VALUES ('EPR_MBH_002', TRUE);
INSERT INTO epr_pharmacoresistance (pseudonyme, statut_pharmacoresistance_confirme) VALUES ('EPR_MBH_005', TRUE);
INSERT INTO epr_pharmacoresistance (pseudonyme, statut_pharmacoresistance_confirme) VALUES ('EPR_AZ_004', TRUE);

-- ---- epr_liste_ae ----
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Valproate de sodium (Depakine)', '50 mg x2/j puis 200 mg x2/j (~30 mg/kg/j)', 'Depuis l''age de 3 mois, en cours', 'Reduction partielle de la frequence des crises', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Clonazepam (Rivotril)', '1 mg/j puis doses variables (1/4 cp x2)', 'Depuis l''age de 3 mois, avec interruptions', 'Reponse partielle', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Phenytoine (Dilantin)', '15 mg/j (5 mg/kg/j)', 'Environ 3-4 mois', 'Amelioration initiale puis arrete', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Prednisolone (Solupred)', 'Non precisee', '2 mois (introduit a 4 mois)', 'Pas d''amelioration', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Hydrocortisone (Cortef)', 'Non precisee', '14 semaines (introduit a 9 mois)', 'Pas d''amelioration', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Levetiracetam (Levet)', '2 ml x2/j (~50-60 mg/kg/j)', 'Plusieurs annees, arrete en 2023 par la mere', 'Inefficacite percue par la famille, non-observance', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Clobazam (Urbanyl)', '1/4 cp x2/j (~0,625 mg/kg/j)', 'Plusieurs mois, remplace par le Rivotril', 'Peu efficace', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Carbamazepine (Tegretol) - 1er essai', '50 mg x2 puis 100 mg x2/j', 'Environ 1 semaine (octobre 2023)', 'Aggravation des crises', 'Effet indesirable');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_001', 'Carbamazepine (Tegretol/Taver) - reintroduction', '15 mg/kg/j, doses progressives', 'Depuis 2024, en cours', 'Amelioration nette, 0 crise/jour, epilepsie bien equilibree', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Valproate de sodium (Depakine)', '50 mg x2/j puis 200 mg x2/j', 'Depuis l''age de 3 mois, en cours', 'Reponse partielle', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Phenytoine (Dilantin)', '15 mg/j (5 mg/kg/j)', 'Environ 3 mois', 'Amelioration initiale', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Clonazepam (Rivotril)', '1 mg/j puis 1/4 cp x2', 'Depuis l''age de 3 mois, en cours', 'Reponse partielle', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Prednisolone (Solupred)', 'Non precisee', '2 semaines (2018)', 'Pas d''amelioration', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Hydrocortisone (Cortef)', 'Non precisee', '50 jours (2019)', 'Pas d''amelioration', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Clobazam (Urbanyl)', '1/4 cp/j (0,625 mg/kg/j)', 'Plusieurs mois', 'Reponse partielle', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Levetiracetam (Levet)', '2 ml x2/j', 'Arrete par la famille avant mai 2022', 'Identifie comme facteur decompensant a l''arret', 'Inefficacite / non-observance');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Phenytoine (protocole aigu)', '15 mg/kg puis 5 mg/kg toutes les 6h', 'Mai 2022 (etat de mal)', 'Pas de recidive sous surveillance', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_002', 'Lamotrigine (Lamictal)', 'Introduction progressive, mai 2022', 'Introduit a la sortie d''hospitalisation', 'Non evalue (fin du dossier)', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Valproate de sodium (Depakine sirop puis chrono)', 'Doses variables', 'Environ 1 an', 'Sans amelioration de la frequence des crises', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Carbamazepine (Tegretol)', 'Non precisee', '3 mois', 'Inefficace', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Association Lamictal + Levet + Urbanyl', 'Non precisee', 'Non precisee', 'Eruption cutanee, cytolyse hepatique, fievre (arret de tous les traitements)', 'Effet indesirable');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Clobazam (Aklonil)', '1/2 comprime par jour', 'Introduit fin 2022', 'Diminution initiale des crises puis echappement apres quelques semaines', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Association Aklonil + Lamictal + Trileptal (oxcarbazepine)', 'Non precisee', 'Fin 2022', 'Sans amelioration, 3 crises/jour', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Clonazepam (Rivotril) a hautes doses', '1 - 1/2 - 1 comprime', 'Environ 1 mois', 'Bonne reponse initiale, libre de crises 1 mois, rechute apres infection bronchique', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Topiramate (Epitomax)', 'Non precisee', 'Non precisee', 'Hallucinations visuelles, agitation psychomotrice ayant motive l''arret', 'Effet indesirable');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Lamotrigine (Lamictal) - reprise', '75 mg x2/j (6 mg/kg/j)', 'En cours en 2024-2025', 'Amelioration progressive de la frequence des crises', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_MBH_005', 'Clobazam (Urbanyl) - association actuelle', '1/2 cp x2/j', 'En cours en 2024-2025', 'Association au Lamictal, poursuite du traitement', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Valproate de sodium (Depakine sirop puis Chrono)', '350 mg x2/j (23 mg/kg/j) puis 500 mg x2/j (28 mg/kg/j), doses ajustees', 'Depuis fevrier 2020, en cours', 'Reponse partielle, dosages plasmatiques difficiles a equilibrer', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Clobazam (Urbanyl)', '1/2 cp/j a 1 cp x2/j selon les periodes, arrets intermittents', 'Depuis janvier 2021, de facon intermittente', 'Reponse partielle, aggravations rapportees a l''arret', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Lamotrigine (Lamictal)', 'Progressive de 25 mg/j a 3 cp x2/j (~4,4 mg/kg/j)', 'Depuis fevrier 2021, en cours', 'Diminution de la frequence des crises, bonne tolerance', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Clonazepam (Rivotril)', '1/4 cp x2/j', 'Introduit en 2025', 'En cours d''evaluation', NULL);
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Levetiracetam (Levet/Lepix puis Epilepta)', '500 mg, doses croissantes', 'Introduit en 2025, switche en 2026 (rupture de stock)', 'Sans amelioration nette, reduit puis change pour probleme de disponibilite', 'Inefficacite');
INSERT INTO epr_liste_ae (pseudonyme, nom_ae, dose, duree, reponse, motif_echec) VALUES ('EPR_AZ_004', 'Topiramate (Epitomax)', 'Non precisee', 'Non obtenue (2026)', 'Non evalue, rupture d''approvisionnement', NULL);

-- ---- epr_eeg ----
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_MBH_001', '2018-10-01', 'Anormal', 'Pattern evocateur d''epilepsie cryptogenique partielle', NULL, FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_MBH_001', '2019-03-01', 'Anormal', 'Activite de base alteree, pointes lentes et pointes-ondes de haut voltage', 'Predominance centrale, decharges de pointes rapides diffuses', FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_MBH_002', '2018-04-05', 'Anormal', 'Pointes-ondes de distribution hemispherique', 'Hemispherique droit', FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_MBH_002', '2020-02-20', 'Anormal', 'Anomalies intercritiques, rythme de fond accelere pour l''age', 'Predominance frontale droite', FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_MBH_005', '2020-09-03', 'Anormal', 'Decharges epileptiques a l''endormissement', 'Fronto-temporal, predominance gauche', FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_AZ_004', '2020-02-28', 'Anormal', 'Rythme de fond ralenti, anomalies paroxystiques generalisees', 'Generalise', TRUE, '2020-02-28', 'Crise tonique generalisee');
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_AZ_004', '2022-02-01', 'Anormal', 'Pattern de pointes-ondes continues du sommeil (POCS) suspecte ; compte-rendu et trace non disponibles', NULL, FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_AZ_004', '2023-04-19', 'Anormal', 'POCS en sommeil ; anomalies centro-temporales bilaterales en veille', 'Centro-temporal bilateral', FALSE, NULL, NULL);
INSERT INTO epr_eeg (pseudonyme, date_eeg, eeg_intercritique, type_anomalie, localisation_foyer, eeg_video_realise, date_eeg_video, type_crise_enregistree) VALUES ('EPR_AZ_004', '2023-07-22', 'Anormal', 'Pointes-ondes generalisees s''organisant en bouffees, pas d''aspect de POCS', 'Generalise', FALSE, NULL, NULL);

-- ---- epr_imagerie ----
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_MBH_001', '2018-03-31', 'Normal', NULL, 'IRM cerebrale a J21 de vie, normale');
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_MBH_002', '2018-03-23', 'Normal', NULL, 'IRM cerebrale a J13 de vie, normale');
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_MBH_002', '2019-03-01', 'Anormal', 'Atrophie cortico-sous-corticale, atrophie du corps calleux (hypoplasique mais complet)', 'Atrophie cortico-sous-corticale epargnant la region parieto-occipitale droite, interessant les lobes temporaux medians sans sclerose mesiale, corps calleux hypoplasique mais complet, absence d''anomalie de migration neuronale');
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_MBH_005', '2020-09-08', 'Normal', NULL, 'IRM cerebrale du 08/09/2020 sans anomalie');
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_MBH_005', '2022-01-15', 'Anormal', 'Hypoplasie du tegmentum pontique, hypersignal diffusion bilateral et symetrique du faisceau tegmental central, elargissement du V4', 'Discrete diminution du volume de la substance blanche du tronc cerebral avec discret elargissement du signal ventriculaire, elargissement passif du V4 et des citernes peri-tronc cerebral et des espaces arachnoidiens fronto-temporaux, pas de lesion epileptogene identifiee');
INSERT INTO epr_imagerie (pseudonyme, date_examen, irm_cerebrale, type_lesion, cr_detaille_texte) VALUES ('EPR_AZ_004', '2020-11-05', 'Normal', NULL, 'IRM cerebrale du 05/11/2020 normale');

-- ---- epr_genetique ----
INSERT INTO epr_genetique (pseudonyme, gene_teste, variant_identifie, classification_acmg, mode_transmission) VALUES ('EPR_MBH_001', 'Whole Exome Sequencing (WES) - patient, frere jumeau, mere et pere', 'Mutation KCNQ2', NULL, 'De novo (a confirmer, recherche en cours chez les parents et le frere)');
INSERT INTO epr_genetique (pseudonyme, gene_teste, variant_identifie, classification_acmg, mode_transmission) VALUES ('EPR_MBH_002', 'Whole Exome Sequencing (WES) - patient, mere et frere', 'Mutation KCNQ2', NULL, 'De novo (a confirmer)');
INSERT INTO epr_genetique (pseudonyme, gene_teste, variant_identifie, classification_acmg, mode_transmission) VALUES ('EPR_MBH_005', 'Panel PAGEM (propose, non realise au moment du dossier)', NULL, NULL, NULL);
INSERT INTO epr_genetique (pseudonyme, gene_teste, variant_identifie, classification_acmg, mode_transmission) VALUES ('EPR_AZ_004', 'Recherche ciblee proposee (caryotype + panel de genes candidats)', NULL, NULL, NULL);

-- ---- epr_alternatives_therapeutiques ----
INSERT INTO epr_alternatives_therapeutiques (pseudonyme, type_alternative, date_debut, reponse) VALUES ('EPR_AZ_004', 'Regime cetogene', NULL, 'Discute avec la famille, non debute au moment du dossier (mai 2026)');

-- ---- epr_suivi ----
INSERT INTO epr_suivi (pseudonyme, statut_dernier_suivi, duree_suivi_mois) VALUES ('EPR_MBH_001', 'Libre de crises', 72);
INSERT INTO epr_suivi (pseudonyme, statut_dernier_suivi, duree_suivi_mois) VALUES ('EPR_MBH_002', 'Decede', 29);
INSERT INTO epr_suivi (pseudonyme, statut_dernier_suivi, duree_suivi_mois) VALUES ('EPR_MBH_005', 'Epilepsie active', 3);
INSERT INTO epr_suivi (pseudonyme, statut_dernier_suivi, duree_suivi_mois) VALUES ('EPR_AZ_004', 'Epilepsie active', 47);

-- ---- coordonnee_patient ----
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('EPR_MBH_001', 'DOS-2020-00145', 'Mohamed Ben Hamouda', '2018-03-10', 'Route de Msaken, Sousse, Tunisie', 'Sousse', '+216 23 456 789', '18100234', 'CNAM-MBH-0001478', 'Ben Hamouda Karim', 'Ben Hamouda Amel', 'Ben Hamouda Mehdi (jumeau, EPR_MBH_002) ; Ben Hamouda Youssef (7 ans)', NULL, 'Mere : crise epileptique en fin de grossesse sous Levetiracetam, sans recidive');
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('EPR_MBH_002', 'DOS-2020-00146', 'Mehdi Ben Hamouda', '2018-03-10', 'Route de Msaken, Sousse, Tunisie', 'Sousse', '+216 23 456 789', '18100235', 'CNAM-MBH-0001479', 'Ben Hamouda Karim', 'Ben Hamouda Amel', 'Ben Hamouda Mohamed (jumeau, EPR_MBH_001) ; Ben Hamouda Youssef (7 ans)', NULL, 'Mere : crise epileptique en cours de grossesse sous Levetiracetam, sans recidive. Patient decede en juin 2022.');
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('EPR_MBH_005', 'DOS-2024-00312', 'Mehdi Ben Hadj Ali', '2016-09-20', 'Village El Alaa, Kairouan, Tunisie', 'Kairouan', '+216 27 654 321', '16090512', 'CNAM-MBH-0005512', 'Ben Hadj Ali Slim', 'Ben Hadj Ali Sonia', 'Ben Hadj Ali Yassine ; Ben Hadj Ali Karim', NULL, 'Consanguinite parentale lointaine (grands-parents cousins) ; antecedents familiaux d''epilepsie et de deficience intellectuelle chez des cousins paternels');
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('EPR_AZ_004', 'DOS-2022-00089', 'Aziz Zouari', '2013-03-15', '15 Rue Farhat Hached, Gabes, Tunisie', 'Gabes', '+216 29 112 233', '13031578', 'CNAM-AZ-0004321', 'Zouari Nabil', 'Zouari Ines', NULL, 'Zouari Salma (7 ans)', 'Mere : paralysie faciale peripherique droite en 2018');
