-- ---- patients ----
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('SEP_AZ_005', 'SEP', '2025-04-07', 16);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('SEP_MBH_003', 'SEP', '2025-04-07', 12);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('SEP_MJ_001', 'SEP', '2026-05-30', 15);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('SEP_MJ_002', 'SEP', '2023-01-09', 15);
INSERT INTO patients (pseudonyme, registre, date_inclusion, age) VALUES ('SEP_ZM_004', 'SEP', '2025-03-19', 16);

-- ---- sep_identification_clinique ----
INSERT INTO sep_identification_clinique (pseudonyme, sexe, gouvernorat_code, date_diagnostic, age_diagnostic_mois, age_premier_symptome_mois) VALUES ('SEP_AZ_005', 'F', 'TUN', '2025-04-13', 192, 192);
INSERT INTO sep_identification_clinique (pseudonyme, sexe, gouvernorat_code, date_diagnostic, age_diagnostic_mois, age_premier_symptome_mois) VALUES ('SEP_MBH_003', 'F', 'ARI', '2025-04-10', 144, 140);
INSERT INTO sep_identification_clinique (pseudonyme, sexe, gouvernorat_code, date_diagnostic, age_diagnostic_mois, age_premier_symptome_mois) VALUES ('SEP_MJ_001', 'M', 'BEN', '2026-06-03', 180, 180);
INSERT INTO sep_identification_clinique (pseudonyme, sexe, gouvernorat_code, date_diagnostic, age_diagnostic_mois, age_premier_symptome_mois) VALUES ('SEP_MJ_002', 'F', 'SFA', '2024-01-11', 181, 156);
INSERT INTO sep_identification_clinique (pseudonyme, sexe, gouvernorat_code, date_diagnostic, age_diagnostic_mois, age_premier_symptome_mois) VALUES ('SEP_ZM_004', 'M', 'NAB', '2025-04-03', 192, 192);

-- ---- sep_antecedents ----
INSERT INTO sep_antecedents (pseudonyme, atcd_familiaux_auto_immuns_neuro, atcd_familiaux_precision, consanguinite_parentale, consanguinite_degre, infections_vaccinations_avant_1er_episode) VALUES ('SEP_AZ_005', FALSE, NULL, FALSE, NULL, 'Rhinorrhée / syndrome grippal léger le 24/03/2025, une semaine avant la 1ère poussée');
INSERT INTO sep_antecedents (pseudonyme, atcd_familiaux_auto_immuns_neuro, atcd_familiaux_precision, consanguinite_parentale, consanguinite_degre, infections_vaccinations_avant_1er_episode) VALUES ('SEP_MBH_003', TRUE, 'Père suivi pour SEP-RR ; frère (17 ans) suivi pour SEP ; hypoacousie chez tante maternelle et cousin maternel (non neuro)', TRUE, '3e degré', 'Vaccination à jour ; épisode fébrile non spécifique en décembre 2024 avant 1er épisode');
INSERT INTO sep_antecedents (pseudonyme, atcd_familiaux_auto_immuns_neuro, atcd_familiaux_precision, consanguinite_parentale, consanguinite_degre, infections_vaccinations_avant_1er_episode) VALUES ('SEP_MJ_001', FALSE, 'Pas d''antécédents familiaux de pathologie neurologique ou psychiatrique', TRUE, NULL, NULL);
INSERT INTO sep_antecedents (pseudonyme, atcd_familiaux_auto_immuns_neuro, atcd_familiaux_precision, consanguinite_parentale, consanguinite_degre, infections_vaccinations_avant_1er_episode) VALUES ('SEP_MJ_002', FALSE, 'Mort fœtale in utero chez la mère ; pas d''antécédents neuro/psy familiaux', FALSE, NULL, 'Tuberculose ganglionnaire (oct. 2021) puis suspicion tuberculose neuroméningée (BK faiblement positif au LCR, fév. 2022), traitée par antituberculeux + corticothérapie 9 mois ; vaccination à jour');
INSERT INTO sep_antecedents (pseudonyme, atcd_familiaux_auto_immuns_neuro, atcd_familiaux_precision, consanguinite_parentale, consanguinite_degre, infections_vaccinations_avant_1er_episode) VALUES ('SEP_ZM_004', TRUE, 'Tante maternelle suivie pour SEP depuis l''âge de 21 ans', FALSE, NULL, 'Syndrome grippal 1 mois avant l''installation du ptosis/diplopie ; vacciné à jour ; rhinite allergique, anémie sous Tardyféron');

-- ---- sep_presentation_initiale ----
INSERT INTO sep_presentation_initiale (pseudonyme, type_premier_evenement, recuperation_complete) VALUES ('SEP_AZ_005', 'tronc_cerebral', 'Partielle');
INSERT INTO sep_presentation_initiale (pseudonyme, type_premier_evenement, recuperation_complete) VALUES ('SEP_MBH_003', 'nevrite_optique', 'Partielle');
INSERT INTO sep_presentation_initiale (pseudonyme, type_premier_evenement, recuperation_complete) VALUES ('SEP_MJ_001', 'polysymptomatique', 'Partielle');
INSERT INTO sep_presentation_initiale (pseudonyme, type_premier_evenement, recuperation_complete) VALUES ('SEP_MJ_002', 'polysymptomatique', 'Non');
INSERT INTO sep_presentation_initiale (pseudonyme, type_premier_evenement, recuperation_complete) VALUES ('SEP_ZM_004', 'tronc_cerebral', 'Partielle');

-- ---- sep_evolution ----
INSERT INTO sep_evolution (pseudonyme, forme_evolutive, severite, date_conversion_sp, date_conversion_sp_non_applicable) VALUES ('SEP_AZ_005', 'RR', 'hautement_active', NULL, TRUE);
INSERT INTO sep_evolution (pseudonyme, forme_evolutive, severite, date_conversion_sp, date_conversion_sp_non_applicable) VALUES ('SEP_MBH_003', 'RR', 'hautement_active', NULL, TRUE);
INSERT INTO sep_evolution (pseudonyme, forme_evolutive, severite, date_conversion_sp, date_conversion_sp_non_applicable) VALUES ('SEP_MJ_001', 'RR', NULL, NULL, TRUE);
INSERT INTO sep_evolution (pseudonyme, forme_evolutive, severite, date_conversion_sp, date_conversion_sp_non_applicable) VALUES ('SEP_MJ_002', 'RR', NULL, NULL, TRUE);
INSERT INTO sep_evolution (pseudonyme, forme_evolutive, severite, date_conversion_sp, date_conversion_sp_non_applicable) VALUES ('SEP_ZM_004', 'RR', 'hautement_active', NULL, TRUE);

-- ---- sep_poussees ----
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_AZ_005', '2025-03-31', 'Tronc cérébral (vestibulaire, oculomoteur)', 'corticoides', FALSE, 3);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_AZ_005', '2025-09-26', 'Tronc cérébral (vestibulaire, sensitivomoteur hémicorps droit)', 'corticoides', TRUE, 2);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_MBH_003', '2025-04-05', 'Nerf optique gauche (névrite optique)', 'corticoides', TRUE, 5);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_MJ_001', '2026-05-26', 'Polysymptomatique : sensitivomoteur + cérébelleux hémicorps droit', 'corticoides', TRUE, 6);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_MJ_002', '2022-12-01', 'Céphalées + hémiparésie gauche', 'aucun', TRUE, NULL);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_MJ_002', '2025-01-01', 'Nerf optique droit (diplopie, strabisme convergent, régressif spontané)', 'aucun', FALSE, NULL);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_ZM_004', '2025-03-19', 'Tronc cérébral (III gauche, ophtalmoplégie internucléaire)', 'corticoides', TRUE, 3);
INSERT INTO sep_poussees (pseudonyme, date_poussee, type_localisation, traitement_poussee, sequelle_post_poussee, edss_associe) VALUES ('SEP_ZM_004', '2025-04-25', 'Tronc cérébral (2e poussée, syndrome vestibulaire central)', 'corticoides', FALSE, 3);

-- ---- sep_edss_visites ----
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_AZ_005', '2025-04-07', 3);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_AZ_005', '2025-09-26', 2);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_AZ_005', '2026-01-05', 0);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_AZ_005', '2026-04-24', 1);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MBH_003', '2025-04-12', 5);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MBH_003', '2025-10-22', 0);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MBH_003', '2026-03-23', 0);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MJ_001', '2026-05-31', 6);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MJ_001', '2026-06-03', 2.5);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_MJ_002', '2025-12-22', 1);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_ZM_004', '2025-03-19', 3);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_ZM_004', '2025-04-11', 2);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_ZM_004', '2025-04-27', 3);
INSERT INTO sep_edss_visites (pseudonyme, date_visite, score_edss) VALUES ('SEP_ZM_004', '2025-09-22', 0);

-- ---- sep_irm ----
INSERT INTO sep_irm (pseudonyme, date_examen, nb_lesions_t2, cr_irm_texte, localisation_peri_ventriculaire, localisation_juxta_corticale, localisation_sous_tentorielle, localisation_moelle, prise_contraste_gd, nb_lesions_rehaussees, nouvelles_lesions_vs_irm_anterieure, atrophie_cerebrale_medullaire) VALUES ('SEP_AZ_005', '2025-04-04', NULL, 'Hypersignaux T2 FLAIR périventriculaires, juxtaventriculaires, corps calleux, capsule interne gauche, sous-corticaux fronto-temporaux bilatéraux ; 1 black hole sous-cortical insulaire gauche ; prise de contraste nodulaire temporale droite et basifrontale droite ; sous-tentoriel : pédoncule cérébelleux moyen droit et bilatéral, mésencéphale, nodule cérébelleux inférieur droit ; pas d''anomalie orbitaire ni médullaire.', TRUE, TRUE, TRUE, FALSE, TRUE, 2, NULL, FALSE);
INSERT INTO sep_irm (pseudonyme, date_examen, nb_lesions_t2, cr_irm_texte, localisation_peri_ventriculaire, localisation_juxta_corticale, localisation_sous_tentorielle, localisation_moelle, prise_contraste_gd, nb_lesions_rehaussees, nouvelles_lesions_vs_irm_anterieure, atrophie_cerebrale_medullaire) VALUES ('SEP_MBH_003', '2025-04-10', NULL, 'Sous-tentoriel : hypersignaux FLAIR nodulaires pédoncules cérébelleux moyens et pont, pas de black hole. Sus-tentoriel : hypersignaux FLAIR/iso T1 substance blanche sous- et périventriculaire bilatérale, aspect en crête de coq, tronc et corps calleux, bras antérieur capsule interne gauche, sous-cortical fronto-pariétal bilatéral, prise de contraste nodulaire périventriculaire carrefour ventriculaire. Orbitaire : hypersignal T2 nerf optique gauche intra-orbitaire non rehaussé ; lésion graisseuse sous-cutanée toit orbite gauche 14x11x6mm (probable kyste dermoïde, non lié à la SEP). Médullaire : lésions hypersignal T2 cordon antérieur/postérieur/latéral C2-C7/D2-D4, pas de prise de contraste.', TRUE, TRUE, TRUE, TRUE, TRUE, 1, NULL, FALSE);
INSERT INTO sep_irm (pseudonyme, date_examen, nb_lesions_t2, cr_irm_texte, localisation_peri_ventriculaire, localisation_juxta_corticale, localisation_sous_tentorielle, localisation_moelle, prise_contraste_gd, nb_lesions_rehaussees, nouvelles_lesions_vs_irm_anterieure, atrophie_cerebrale_medullaire) VALUES ('SEP_MJ_001', '2026-05-29', NULL, 'Anomalies de signal substance blanche périventriculaire latérale gauche, pédoncule cérébral gauche, pontique et cérébelleux gauche, ovalaires, hypersignal T2 FLAIR, isosignal T1, discret hypersignal diffusion sans restriction ADC ; prise de contraste homogène des lésions périventriculaires et pontiques après gadolinium. Médullaire : sans anomalie.', TRUE, FALSE, TRUE, FALSE, TRUE, NULL, NULL, FALSE);
INSERT INTO sep_irm (pseudonyme, date_examen, nb_lesions_t2, cr_irm_texte, localisation_peri_ventriculaire, localisation_juxta_corticale, localisation_sous_tentorielle, localisation_moelle, prise_contraste_gd, nb_lesions_rehaussees, nouvelles_lesions_vs_irm_anterieure, atrophie_cerebrale_medullaire) VALUES ('SEP_MJ_002', '2023-11-28', NULL, 'Comparativement à l''IRM du 24/04/2023 : nouvelle lésion nodulaire frontale droite hypersignal T2 FLAIR/diffusion avec restriction ADC, rehaussée après gadolinium (8mm) ; lésions ovalaires substance blanche diffuse bilatérale quasi stables, aspect en crête de coq, 2 lésions genou/tronc du corps calleux ; lésion sous-tentorielle pédoncule cérébelleux moyen droit stable. Médullaire : cône terminal normal en D12, sans anomalie à ce stade (atteinte médullaire D11 apparue ultérieurement en 2025).', TRUE, TRUE, TRUE, FALSE, TRUE, 1, TRUE, FALSE);
INSERT INTO sep_irm (pseudonyme, date_examen, nb_lesions_t2, cr_irm_texte, localisation_peri_ventriculaire, localisation_juxta_corticale, localisation_sous_tentorielle, localisation_moelle, prise_contraste_gd, nb_lesions_rehaussees, nouvelles_lesions_vs_irm_anterieure, atrophie_cerebrale_medullaire) VALUES ('SEP_ZM_004', '2025-03-19', NULL, 'Anomalie de signal ovoïde latéro-mésencéphalique gauche rehaussée après gadolinium ; multiples anomalies nodulaires ovoïdes substance blanche périventriculaire sous-corticale fronto-pariétale, certaines en hyposignal (black holes), aspect en crête de coq, non rehaussées après gadolinium. Pas d''anomalie médullaire.', TRUE, TRUE, TRUE, FALSE, TRUE, 1, NULL, FALSE);

-- ---- sep_biologie_lcr ----
INSERT INTO sep_biologie_lcr (pseudonyme, date_prelevement, bandes_oligoclonales, index_chaines_kappa, index_igg, anticorps_type, anticorps_autre_texte) VALUES ('SEP_AZ_005', '2025-04-08', NULL, NULL, NULL, NULL, 'PL faite, cytochimie normale ; anti-AQP4/anti-MOG demandés (résultats non précisés dans le dossier)');
INSERT INTO sep_biologie_lcr (pseudonyme, date_prelevement, bandes_oligoclonales, index_chaines_kappa, index_igg, anticorps_type, anticorps_autre_texte) VALUES ('SEP_MJ_001', '2026-05-30', 'Negatif', NULL, NULL, 'NMO_IgG_MOG', 'Anti-MOG sang/LCR négatifs, anti-AQP4 sang négatif. LCR : 1 élément blanc, glucorachie 3,66 mmol/L, protéinorachie 0,16 g/L, chlorurachie 117 mmol/L (tout normal).');
INSERT INTO sep_biologie_lcr (pseudonyme, date_prelevement, bandes_oligoclonales, index_chaines_kappa, index_igg, anticorps_type, anticorps_autre_texte) VALUES ('SEP_MJ_002', '2025-09-17', NULL, NULL, 2.4, NULL, 'IEPP : index IgG à 2,4 avec synthèse intrathécale. LCR : 8 éléments blancs, glucorachie normale 2,98, protéinorachie discrètement élevée 0,57 g/L, lactorachie normale 1,42.');
INSERT INTO sep_biologie_lcr (pseudonyme, date_prelevement, bandes_oligoclonales, index_chaines_kappa, index_igg, anticorps_type, anticorps_autre_texte) VALUES ('SEP_ZM_004', '2025-03-19', NULL, NULL, NULL, 'NMO_IgG_MOG', 'LCR aspect eau de roche, 8 éléments blancs, protéinorachie 0,42 g/L, glucorachie et chlorurachie normales. Anti-MOG et anti-AQP4 (sang) négatifs le 25/03/2025 ; isoélectrofocalisation LCR en cours.');

-- ---- sep_potentiels_evoques ----
INSERT INTO sep_potentiels_evoques (pseudonyme, date_examen, pev, pes, pea, anomalie_texte) VALUES ('SEP_MBH_003', '2025-04-12', 'Anormal', NULL, NULL, 'PEV fait en période de baisse d''acuité visuelle sévère (1/20 œil gauche), résultat détaillé non précisé');
INSERT INTO sep_potentiels_evoques (pseudonyme, date_examen, pev, pes, pea, anomalie_texte) VALUES ('SEP_MJ_001', '2026-06-03', 'Normal', NULL, NULL, NULL);
INSERT INTO sep_potentiels_evoques (pseudonyme, date_examen, pev, pes, pea, anomalie_texte) VALUES ('SEP_ZM_004', '2025-03-21', 'Normal', NULL, NULL, NULL);

-- ---- sep_traitement_fond ----
INSERT INTO sep_traitement_fond (pseudonyme, molecule, ligne_therapeutique, date_debut, date_fin, motif_switch, effets_indesirables, observance) VALUES ('SEP_AZ_005', 'Rituximab', '1ère ligne', '2025-11-21', NULL, NULL, NULL, 'Oui');
INSERT INTO sep_traitement_fond (pseudonyme, molecule, ligne_therapeutique, date_debut, date_fin, motif_switch, effets_indesirables, observance) VALUES ('SEP_MBH_003', 'Rituximab', '1ère ligne', '2025-10-01', NULL, NULL, 'Réaction cytokinique bénigne (prurit de gorge) à la 2e perfusion, résolutive après ralentissement du débit', 'Oui');
INSERT INTO sep_traitement_fond (pseudonyme, molecule, ligne_therapeutique, date_debut, date_fin, motif_switch, effets_indesirables, observance) VALUES ('SEP_MJ_001', 'Acétate de glatiramère', '1ère ligne', '2026-06-18', NULL, NULL, NULL, NULL);
INSERT INTO sep_traitement_fond (pseudonyme, molecule, ligne_therapeutique, date_debut, date_fin, motif_switch, effets_indesirables, observance) VALUES ('SEP_MJ_002', 'Rituximab', '1ère ligne', '2025-12-22', NULL, NULL, NULL, 'Oui');
INSERT INTO sep_traitement_fond (pseudonyme, molecule, ligne_therapeutique, date_debut, date_fin, motif_switch, effets_indesirables, observance) VALUES ('SEP_ZM_004', 'Rituximab', '1ère ligne', '2025-06-13', NULL, NULL, 'Syndrome pseudo-grippal (toux, gorge érythémateuse) avant la 2e perfusion → cure décalée de 5 jours', 'Partielle');

-- ---- sep_suivi ----
INSERT INTO sep_suivi (pseudonyme, date_dernier_suivi, statut_dernier_suivi, score_edss_dernier, impact_scolaire_cognitif, impact_precision, score_cognitif, score_cognitif_non_applicable) VALUES ('SEP_AZ_005', '2026-06-06', 'Stable', 1, FALSE, NULL, 90, FALSE);
INSERT INTO sep_suivi (pseudonyme, date_dernier_suivi, statut_dernier_suivi, score_edss_dernier, impact_scolaire_cognitif, impact_precision, score_cognitif, score_cognitif_non_applicable) VALUES ('SEP_MBH_003', '2026-05-08', 'Stable', 0, FALSE, NULL, NULL, TRUE);
INSERT INTO sep_suivi (pseudonyme, date_dernier_suivi, statut_dernier_suivi, score_edss_dernier, impact_scolaire_cognitif, impact_precision, score_cognitif, score_cognitif_non_applicable) VALUES ('SEP_MJ_001', '2026-06-18', 'Stable', 2.5, FALSE, NULL, NULL, TRUE);
INSERT INTO sep_suivi (pseudonyme, date_dernier_suivi, statut_dernier_suivi, score_edss_dernier, impact_scolaire_cognitif, impact_precision, score_cognitif, score_cognitif_non_applicable) VALUES ('SEP_MJ_002', '2026-04-06', 'Stable', 1, TRUE, 'Troubles mnésiques et de concentration transitoires ; test des 5 mots normal (5/5)', NULL, TRUE);
INSERT INTO sep_suivi (pseudonyme, date_dernier_suivi, statut_dernier_suivi, score_edss_dernier, impact_scolaire_cognitif, impact_precision, score_cognitif, score_cognitif_non_applicable) VALUES ('SEP_ZM_004', '2026-05-29', 'Stable', 0, TRUE, 'Fléchissement scolaire, syndrome dépressif et troubles du comportement (oppositionnel), suivi en pédopsychiatrie, score SDMT 46/90', 46, FALSE);

-- ---- coordonnee_patient ----
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('SEP_AZ_005', 'DOS-2025-00512', 'Amira Zoghlami', '2009-02-14', '12 Rue des Jasmins, Ariana, Tunisie', 'Ariana', '+216 20 111 222', '09512345', 'CNAM-AZ-0005512', 'Zoghlami Kamel', 'Zoghlami Sana', 'Zoghlami Youssef (14 ans)', NULL, NULL);
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('SEP_MBH_003', 'DOS-2025-00487', 'Malek Ben Hassine', '2013-01-20', '45 Avenue Habib Bourguiba, Nabeul, Tunisie', 'Nabeul', '+216 22 333 444', '13487654', 'CNAM-MBH-0003487', 'Ben Hassine Fathi', 'Ben Hassine Leila', 'Ben Hassine Sami (17 ans)', 'Ben Hassine Rania (15 ans)', 'Hypoacousie familiale (tante maternelle, cousin)');
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('SEP_MJ_001', 'DOS-2026-00104', 'Mehdi Jendoubi', '2011-03-05', '7 Rue de Carthage, Ben Arous, Tunisie', 'Ben Arous', '+216 24 555 666', '11104321', 'CNAM-MJ-0001104', 'Jendoubi Nabil', 'Jendoubi Wafa', NULL, 'Jendoubi Ines (17 ans)', NULL);
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('SEP_MJ_002', 'DOS-2023-00021', 'Maryam Jaouadi', '2007-12-09', '3 Rue Ibn Khaldoun, Sfax, Tunisie', 'Sfax', '+216 25 777 888', '07021987', 'CNAM-MJ-0002021', 'Jaouadi Slim', 'Jaouadi Amel', NULL, 'Jaouadi Yosra (19 ans)', 'Mort fœtale in utero chez la mère');
INSERT INTO coordonnee_patient (pseudonyme, numero_dossier, nom_prenom, date_naissance, adresse, origine, telephone, cin, num_cnam, nom_prenom_pere, nom_prenom_mere, frere, soeur, autre_antecedent) VALUES ('SEP_ZM_004', 'DOS-2025-00398', 'Zied Mansouri', '2009-03-19', '21 Rue de la République, Bizerte, Tunisie', 'Bizerte', '+216 26 999 000', '09398765', 'CNAM-ZM-0004398', 'Mansouri Adel', 'Mansouri Souad', NULL, NULL, 'Tante maternelle suivie pour SEP depuis 21 ans');